# Generated by Django 3.2.9 on 2021-12-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_id', models.CharField(max_length=200)),
                ('followed_trainline', models.CharField(max_length=200)),
            ],
        ),
    ]
