# Generated by Django 3.2.9 on 2021-12-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='followed_trainline',
            new_name='followed_trainline_name',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='followed_operator_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
