# Generated by Django 3.2.9 on 2021-12-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_delay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininfo',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='traininfo',
            name='railway',
        ),
        migrations.AddField(
            model_name='traininfo',
            name='operator_en',
            field=models.CharField(default='undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='traininfo',
            name='operator_ja',
            field=models.CharField(default='undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='traininfo',
            name='railway_en',
            field=models.CharField(default='undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='traininfo',
            name='railway_ja',
            field=models.CharField(default='undefined', max_length=200),
        ),
    ]
