# Generated by Django 3.2.9 on 2021-12-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_delay', '0002_auto_20211210_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='traininfo',
            old_name='information',
            new_name='information_en',
        ),
        migrations.AddField(
            model_name='traininfo',
            name='information_ja',
            field=models.CharField(default='deadfield', max_length=2000),
            preserve_default=False,
        ),
    ]
